{
    "name": "Gym Management (Otomater)",
    "version": "19.0.1.0.0",
    "category": "Customizations",
    "summary": "Gym Town - members, memberships, attendance, trainers, health, workouts, diets, payments and dashboards",
    "description": "Professional gym management on Odoo 19: controlled membership/plan/payment workflows, "
                   "strict health-data security, accounting integration and a dashboard API for the Next.js front end.",
    "author": "Otomater",
    "website": "https://otomater.com",
    "license": "OPL-1",
    "depends": ["base", "mail", "hr", "account"],
    "data": [
        "security/gym_security.xml",
        "security/ir.model.access.csv",
        "security/gym_rules.xml",
        "data/gym_sequences.xml",
        "data/gym_data.xml",
        "wizard/reason_wizard_views.xml",
        "views/trainer_views.xml",
        "views/member_views.xml",
        "views/membership_views.xml",
        "views/health_views.xml",
        "views/workout_diet_views.xml",
        "views/attendance_appointment_views.xml",
        "views/payment_views.xml",
        "views/misc_views.xml",
        "views/gym_menus.xml",
        "views/demo_views.xml",
        "views/site_views.xml",
        "data/gym_cron.xml",
    ],
    "installable": True,
    "application": True,
}
